# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # nct6683: Driver for motherboard probes
  boot.kernelModules = [ "kvm-amd" "nct6683" ];
  boot.extraModulePackages = [ ];
  boot.zfs.extraPools = [ "hdd-backup" ];

  fileSystems."/" =
    { device = "/dev/disk/by-id/nvme-WD_Green_SN350_2TB_224805467712-part2";
      fsType = "ext4";
    };

  fileSystems."/boot" = {
    device = "/dev/disk/by-id/nvme-WD_Green_SN350_2TB_224805467712-part1";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.forceImportRoot = false; 
  services.zfs.trim.enable = true;
  fileSystems."/hdd-backup" = {
    device = "hdd-backup";
    fsType = "zfs";
  };

  swapDevices = [ ];


  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp42s0.wakeOnLan.enable = true;
  networking.hostId = "82e4e991";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
